TARGET       := geblaat_botmodule_cbotmod
PROJ_DIR     := ../../..
PCDEV_ROOT   := $(PROJ_DIR)/pcdev
OUT_DIR      := $(PROJ_DIR)/out
SRC_DIR      := $(PROJ_DIR)/src

BUILD_LIBRARY=D

C_INCLUDES += $(SRC_DIR)
C_INCLUDES += $(SRC_DIR)/botmodule
C_SRC      += $(SRC_DIR)/botmodule/cbotmod.c

include $(PCDEV_ROOT)/build/make/all.mk



