all:
	make -j -C pluginloader
	make -j -C core
	make -j -C client/bot
	make -j -C botmodules/test
	make -j -C botmodules/cbotmod
	make -j -C connection/tcp
	make -j -C protocol/irc
	make -j -C connection/libretls

